defmodule Orbitly.Repo.Migrations.RemoveClickEventCountry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:click_events) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :country
    # end
    # 
  end

  def down do
    # alter table(:click_events) do
    # This is the `down` migration of the statement:
    #
    #     remove :country
    #
    # 
    # add :country, :text
    # end
    # 
  end
end
