defmodule Orbitly.Repo.Migrations.AddLinkDescription do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:links) do
      add :description, :text
    end
  end

  def down do
    alter table(:links) do
      remove :description
    end
  end
end
