defmodule Orbitly.Repo.Migrations.AddShortenerResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :admin, :boolean, null: false
    end

    create table(:links, primary_key: false) do
      add :owner_id,
          references(:users,
            column: :id,
            name: "links_owner_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :domain_id,
          references(:domains,
            column: :id,
            name: "links_domain_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :password_hash, :text
      add :expires_at, :utc_datetime
      add :target_url, :text, null: false
      add :slug, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:domains, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :active, :boolean, null: false
      add :is_primary, :boolean, null: false
      add :hostname, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:links, [:domain_id, :slug], name: "links_unique_slug_per_domain_index")

    create unique_index(:domains, [:hostname], name: "domains_unique_hostname_index")
  end

  def down do
    drop_if_exists unique_index(:domains, [:hostname], name: "domains_unique_hostname_index")

    drop_if_exists unique_index(:links, [:domain_id, :slug],
                     name: "links_unique_slug_per_domain_index"
                   )

    drop table(:domains)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `links` table without the `links_domain_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `links` table without the `links_owner_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:links)

    alter table(:users) do
      remove :admin
    end
  end
end
