defmodule Orbitly.Repo.Migrations.AddClickEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:click_events, primary_key: false) do
      add :link_id,
          references(:links,
            column: :id,
            name: "click_events_link_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :country, :text
      add :referrer, :text
      add :user_agent, :text
      add :ip, :text
      add :occurred_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `click_events` table without the `click_events_link_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:click_events)
  end
end
